---
- name: Create instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: accessdudab
    instance_type: t2.micro
    security_group: launch-wizard-14
    image: ami-0817d428a6fb68645
    region: us-east-1
    inventory_dir: /inventory/database
    
  tasks:
    - name: Launch instance
      ec2:
        key_name: "{{ keypair }}"
        region: "{{ region }}" 
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: yes   
        vpc_subnet_id: subnet-c1cf7da6 
        count : 1
        assign_public_ip: yes
      register: ec2  
    
    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: database
        inventory_dir: '{{ inventory_dir }}'
      with_items: "{{ ec2.instances }}"
      
    - name: Create SSH Group to login dynamically to EC2 Instance
      add_host: 
        hostname: "{{ item.public_ip }}"
        groupname: ec2_server
      with_items: '{{ ec2.instances }}'

    - name: Wait for SSH to come up
      wait_for: 
        host: "{{ item.public_ip }}" 
        port: 22
        delay: 10
        timeout: 320
        state: started
      with_items: '{{ ec2.instances }}'

- hosts: ec2_server
  become: yes
  remote_user: ubuntu 
  gather_facts: yes
  
  tasks:
  - name: apt update
    become: yes
    become_user: root
    apt: 
      update_cache: True 
      name: [openssl, libssl-dev, libssl-dev,libssl-dev]
      state: present
  - name: Install pip
    apt: 
      name: python3-pip, python3-dev, libpq-dev    
      update_cache: True 
      state: present
  - name: install postgresql
    apt: name ={{item}}
    with_items:
        postgreasql
        postgreasql-contrib
        libpq-dev
        python-psycopg2
  - name: Make sure psycopg2 is installed
    pip:
      name: 
        - psycopg2
        - PyMySQL
        
- hosts: ec2_server
  become: yes
  remote_user: ubuntu 
  gather_facts: yes  
  vars_files:
    - vars/main.yml
  roles:
    - geerlingguy.postgresql

- hosts: ec2_server
  become: yes
  remote_user: ubuntu 
  gather_facts: yes
  
  tasks:
  - name: uncomment line
    lineinfile:
      path: /etc/postgresql/10/main/postgresql.conf
      regexp: '^#(.*Uncomment this line.*)'
      line: listen_addresses = '*'
      
  - name: add line   
    lineinfile:
      path: /etc/postgresql/10/main/pg_hba.conf
      line: host all all 0.0.0.0/0 md5

  - name: liberar firewall
    become: yes
    command: sudo ufw allow 5432/tcp

  - name: reiniciar postgres
    become: yes
    command: sudo systemctl restart postgresql




  





